# __version__.py
# autogenerated by poetry-hooks 0.1.0

__version__ = "0.1.0"
__title__ = "aqneodriver"
__authors__ = ["Justin Vrana <justin.vrana@gmail.com>"]
__repository__ = ""
__homepage__ = "https://github.com/jvrana/AquariumToNeo4jETL"
__description__ = ""
__maintainers__ = ""
__readme__ = ""
__license__ = ""
